FROM quay.io/jupyter/pytorch-notebook:cuda12-latest

USER ${NB_UID}

# Install Lightning
RUN pip install --pre --no-cache-dir lightning && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Install MLFlow and pynvml library used by MLFlow for monitoring NVIDIA GPU
RUN pip install --pre --no-cache-dir pynvml && \
    pip install --pre --no-cache-dir mlflow && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN pip install --no-cache-dir \
        transformers==4.40.0 \
        datasets==2.19.0 \
        trl==0.8.6 \
        peft==0.10.0 \
        bitsandbytes==0.45.5 \
        evaluate rouge-score \
        accelerate              \
    && fix-permissions "${CONDA_DIR}" \
    && fix-permissions "/home/${NB_USER}"
