name: ray_cluster
services:
  # ────────────────────────────────────────────────────────────
  # MinIO object‑store (checkpoints, datasets, models)
  # ───────────────────────────────

  # Creates the bucket `ray` if it does not yet exist
  minio-create-bucket:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://129.114.25.240:9001 your-access-key your-secret-key &&
      if ! mc ls minio/ray; then
        mc mb minio/ray &&
        echo 'Bucket ray created';
      else
        echo 'Bucket ray already exists';
      fi"

  # ────────────────────────────────────────────────────────────
  # Ray head‑node (Prometheus + metrics provisioning files)
  # ────────────────────────────────────────────────────────────
  ray-head:
    image: rayproject/ray:2.42.1
    container_name: ray-head
    command: |
      /bin/sh -c "
      mkdir -p /tmp/ray &&
      chown -R root:root /tmp/ray &&
      ray metrics launch-prometheus &&
      ray start --head --port=6379 --dashboard-host=0.0.0.0 --block --metrics-export-port=8080"
    ports:
      - "6379:6379"
      - "8265:8265"
      - "8080:8080"
      - "8090:8090"
      - "9090:9090"
    shm_size: "12g"
    volumes:
      - ray_tmp:/tmp/ray          # read‑write
    environment:
      - RAY_GRAFANA_HOST=http://grafana:3000
      - RAY_GRAFANA_IFRAME_HOST=http://${HOST_IP}:3000
      - RAY_PROMETHEUS_HOST=http://ray-head:9090
      - RAY_PROMETHEUS_NAME=Prometheus
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_ENDPOINT_URL=http://129.114.25.240:9001
    user: root

  # ────────────────────────────────────────────────────────────
  # Grafana dashboard (reads Ray’s provisioning files)
  # ────────────────────────────────────────────────────────────
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    entrypoint: |
      /bin/sh -c "
      while [ ! -f /tmp/ray/session_latest/metrics/grafana/grafana.ini ]; do
        echo 'Waiting for Grafana config files...'
        sleep 2
      done
      /run.sh --config /tmp/ray/session_latest/metrics/grafana/grafana.ini"
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana   # dashboards & DB
      - ray_tmp:/tmp/ray:ro                # Ray metrics, read‑only
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_PATHS_PROVISIONING=/tmp/ray/session_latest/metrics/grafana/provisioning
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_DATABASE_TYPE=sqlite3
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    depends_on:
      - ray-head

  # ────────────────────────────────────────────────────────────
  # GPU workers
  # ────────────────────────────────────────────────────────────
  ray-worker-1:
    image: rayproject/ray:2.42.1-gpu
    container_name: ray-worker-0
    command: ["ray", "start", "--address=ray-head:6379", "--num-cpus=32", "--num-gpus=1", "--block"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: ["gpu"]
              device_ids: ["0"]
    environment:
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_ENDPOINT_URL=http://129.114.25.240:9001
    shm_size: "12g"
    volumes:
      - /mnt/LLMData:/mnt:ro 
    depends_on:
      - ray-head

  ray-worker-2:
    image: rayproject/ray:2.42.1-gpu
    container_name: ray-worker-1
    command: ["ray", "start", "--address=ray-head:6379","--num-cpus=32", "--num-gpus=1", "--block"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: ["gpu"]
              device_ids: ["1"]
    environment:
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_ENDPOINT_URL=http://129.114.25.240:9001
    shm_size: "12g"
    volumes:
      - /mnt/LLMData:/mnt:ro 
    depends_on:
      - ray-head

# ────────────────────────────────────────────────────────────
# Named & external volumes
# ────────────────────────────────────────────────────────────
volumes:
  grafana_storage:           # dashboards & Grafana DB
  ray_tmp:                   # Ray + Grafana metrics hand‑off
  
