FROM quay.io/jupyter/pytorch-notebook:cuda12-pytorch-2.5.1


USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends libopenmpi-dev && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb && \
        dpkg -i cuda-keyring_1.1-1_all.deb && \
        rm cuda-keyring_1.1-1_all.deb && \
        apt-get update && \
        apt-get -y install cudnn9-cuda-12


USER ${NB_UID}
#  --extra-index-url is recommended by NVIDIA so pip picks up the wheel from NGC
RUN pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com \
        tensorrt-llm && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"


ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/tensorrt_llm/lib"
